export const IMAGES = {
  LOGO: require("../assets/images/logo.png"),
  AVATAR: require("../assets/images/avatar.png"),
  SCAN1: require("../assets/images/scan1.png"),
  SCAN2: require("../assets/images/scan2.png"),
  SCAN3: require("../assets/images/scan3.png"),
  ARROW: require("../assets/images/arrow.png"),
  DETAILS: require("../assets/images/details.png"),
  EDIT: require("../assets/images/edit.png"),
  TRUE: require("../assets/images/true.png"),
  AVATAR1: require("../assets/images/avatar1.png"),
  LANGUAGE: require("../assets/images/language.png"),
  LOGOUT: require("../assets/images/logout.png"),
  SMALL_ARROW: require("../assets/images/smallArrow.png"),
  PROFILE: require("../assets/images/profile.png"),
  LOCK: require("../assets/images/lock.png"),
  CHANGE_PASSWORD: require("../assets/images/changePass.png"),
  CROSS: require("../assets/images/cross.png"),
  USER: require("../assets/images/user.png"),
  HOME: require("../assets/images/home.png"),
  SCAN_SHIPMENT: require("../assets/images/scanShip.png"),
};
